services:
  step-ca:
    image: docker.io/smallstep/step-ca
    environment:
      - DOCKER_STEPCA_INIT_NAME=Alfresco
      - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,$(hostname -f)
    volumes:
      - ./step:/home/step
    ports:
      - "9000:9000"